spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
--- #api-server
lost-ark:
  api-key: ${LOST-ARK-API-KEY}
  market-api: "https://developer-lostark.game.onstove.com/markets/items"
  user-auth-host: "https://lostark.game.onstove.com/Community/Free/Views/{url_number}"
--- #swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true